"use server";

export async function translateText(text: string, targetLang: string = 'en') {
    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

    if (!GEMINI_API_KEY) {
        console.error("Missing GEMINI_API_KEY in .env");
        return { error: "Translation AI not configured" };
    }

    try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`;

        const prompt = `Translate the following text into the ISO-639-1 language code '${targetLang}'. Return ONLY the translated text. Do not include any explanations, quotes, or markdown formatting.\n\nText to translate: ${text}`;

        const payload = {
            contents: [{
                parts: [{ text: prompt }]
            }],
            generationConfig: {
                temperature: 0.1,
                maxOutputTokens: 256
            }
        };

        const response = await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const errorData = await response.json();
            console.error("Gemini Translate Error:", errorData);
            return { error: "AI translation rejected the request." };
        }

        const data = await response.json();

        let translatedText = data?.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!translatedText) {
            console.error("Unexpected Gemini Payload structure", data);
            return { error: "Failed to parse AI response" };
        }

        // Clean up any extra whitespace or newlines generated by the LLM
        return { translatedText: translatedText.trim(), provider: 'Gemini' };

    } catch (e: any) {
        console.error("Gemini Translation Exception:", e);
        return { error: "Failed to translate message." };
    }
}
